export const ActionTypes = {
    SET_LOGGED_IN_USER: 'SET_LOGGED_IN_USER',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
    USER_LOGIN_IN_PROGRESS: 'USER_LOGIN_IN_PROGRESS',
    USER_LOGOUT: 'USER_LOGOUT',
}
